# Generated by Django 4.2.13 on 2024-08-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="sate",
            new_name="state",
        ),
    ]
