# Generated by Django 4.2.9 on 2024-08-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_profile_old_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="date",
            new_name="date_ordered",
        ),
    ]
