# Generated by Django 4.2.9 on 2024-08-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_rename_date_order_date_ordered"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="date_ordered",
            new_name="date",
        ),
    ]
