# Generated by Django 4.2.9 on 2024-08-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_rename_date_ordered_order_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Category",
            new_name="category",
        ),
    ]
