# Generated by Django 4.2.9 on 2024-08-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_rename_shipping_address1_order_shipping_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_mathod",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
