# Generated by Django 4.2.9 on 2024-08-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_order_payment_mathod_order_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_mathod",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
