# Generated by Django 4.2.9 on 2024-08-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0007_rename_payment_mathod_order_payment_method"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="data_ordered",
            new_name="date_ordered",
        ),
    ]
