# Generated by Django 4.2.9 on 2024-08-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0008_rename_data_ordered_order_date_ordered"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipped",
            field=models.BooleanField(default=False),
        ),
    ]
