# Generated by Django 4.2.9 on 2024-08-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0009_order_shipped"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_shipped",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
