# Generated by Django 4.2.9 on 2024-08-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0010_order_date_shipped"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="payment_method",
            field=models.CharField(default="COD", max_length=255),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="shipping_phone",
            field=models.CharField(default="COD", max_length=255),
            preserve_default=False,
        ),
    ]
