# Generated by Django 4.2.9 on 2024-08-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0011_shippingaddress_payment_method_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="shipping_adress2",
            new_name="shipping_address2",
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="payment_method",
            field=models.CharField(max_length=255),
        ),
    ]
